### PR TITLE
Fix for potential issue retrieving policies from rego

### PR DESCRIPTION
**Pull request by Cerfoglg**
## Proposed changes

Sometimes, due to automatic performance optimizations done by OPA, the http.send function in rego isn't carried out, causing policies not to be retrieved and resulting in 403 responses.

Moving the retrieval of the policies to a lua filter in the envoy and passing it to opa ensured this doesn't happen anymore.

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [Contributor License Agreement][cla]
- [x] I have updated the [RELEASE NOTES][release]
- [x] I have added tests that prove my fix is effective or that my
      feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion
by explaining why you chose the solution you did and what alternatives
you considered, etc...

[cla]: https://raw.githubusercontent.com/orchestracities/anubis/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/anubis/blob/master/CONTRIBUTING.md
    "Contributing to Anubis"
[release]: https://github.com/orchestracities/anubis/blob/master/RELEASE_NOTES.md
    "Anubis Release Notes"

### CODE REVIEW

**Comment by chicco785** [comment]
this is rather weird, also because by default caching is off:
https://www.openpolicyagent.org/docs/latest/policy-reference/#http

Could it be that it takes some time to flush data in the database? How did you verify the issue mentioned?

**Comment by Cerfoglg** [comment]
> this is rather weird, also because by default caching is off: https://www.openpolicyagent.org/docs/latest/policy-reference/#http
> 
> Could it be that it takes some time to flush data in the database? How did you verify the issue mentioned?

It's mentioned here https://www.openpolicyagent.org/docs/latest/policy-reference/ , under the http.send function description.

It's not a caching mechanism, it's some sort of automatic optimisation for rego that ends up not firing off those requests. I'm not sure how exactly it decides, but after making this change I have't been able to get the scripts to fail again like we saw happen before, so either way this is probably better in the long run.

**Comment by chicco785** [comment]
> > this is rather weird, also because by default caching is off: https://www.openpolicyagent.org/docs/latest/policy-reference/#http
> > Could it be that it takes some time to flush data in the database? How did you verify the issue mentioned?
> 
> It's mentioned here https://www.openpolicyagent.org/docs/latest/policy-reference/ , under the http.send function description.
> 
> It's not a caching mechanism, it's some sort of automatic optimisation for rego that ends up not firing off those requests. I'm not sure how exactly it decides, but after making this change I have't been able to get the scripts to fail again like we saw happen before, so either way this is probably better in the long run.

what is weird though, is that this does not happen with sql-lite right? why this makes a difference to OPA???

regardless, as mentioned, if that function has issues, better having a new built-in, rather than using lua.

>This built-in function must not be used for effecting changes in external systems as OPA does not guarantee that the statement will be executed due to automatic performance optimizations that are applied during policy evaluation.

if that's the case, i.e. the call is not executed, this should be easy to spot both in OPA and in the api, right?

**Comment by Cerfoglg** [comment]
> what is weird though, is that this does not happen with sql-lite right? why this makes a difference to OPA???

I believe I did see it happen occasionally with sqlite, but rarely. It's possible that the reason it happens more with postgres is that postgres takes up more resources, and thus causes these rego optimisation to happen more frequently.

> 
> regardless, as mentioned, if that function has issues, better having a new built-in, rather than using lua.

That's the only one built-in. Rego isn't really meant to be used to make HTTP calls, so it doesn't have much support there.

**Comment by chicco785** [comment]
> > what is weird though, is that this does not happen with sql-lite right? why this makes a difference to OPA???
> 
> I believe I did see it happen occasionally with sqlite, but rarely. It's possible that the reason it happens more with postgres is that postgres takes up more resources, and thus causes these rego optimisation to happen more frequently.
> 
> > regardless, as mentioned, if that function has issues, better having a new built-in, rather than using lua.
> 
> That's the only one built-in. Rego isn't really meant to be used to make HTTP calls, so it doesn't have much support there.

in fact, as by first reply, the idea would be to build a custom one:

> Also, even in the case the issue you spotted is correct, it would better to create a new runtime function in go rather than inventing weird things with lua on request time: https://www.openpolicyagent.org/docs/latest/extensions/#custom-built-in-functions-in-go

**Comment by Cerfoglg** [comment]
> > > what is weird though, is that this does not happen with sql-lite right? why this makes a difference to OPA???
> > 
> > 
> > I believe I did see it happen occasionally with sqlite, but rarely. It's possible that the reason it happens more with postgres is that postgres takes up more resources, and thus causes these rego optimisation to happen more frequently.
> > > regardless, as mentioned, if that function has issues, better having a new built-in, rather than using lua.
> > 
> > 
> > That's the only one built-in. Rego isn't really meant to be used to make HTTP calls, so it doesn't have much support there.
> 
> in fact, as by first reply, the idea would be to build a custom one:
> 
> > Also, even in the case the issue you spotted is correct, it would better to create a new runtime function in go rather than inventing weird things with lua on request time: https://www.openpolicyagent.org/docs/latest/extensions/#custom-built-in-functions-in-go

That warning about automatic optimisation is there on the documentation about custom functions as well regarding HTTP operations, so building a custom function won't solve that problem, since these appear to be I/O optimisations OPA is doing. I couldn't find any configuration for OPA to change this, and error/exception handling in rego isn't really a thing. Hence why I chose to use the filters to retrieved the policy data from the API prior to the OPA evaluation.

**Comment by chicco785** [comment]
at the current stage, I don't think we should merge this PR

**Comment by chicco785** [comment]
> at the current stage, I don't think we should merge this PR

also, considering the ultimate goal is to push data from the api into opa, it's non sense to use this work around, unless the issue pops up again

**Comment by Cerfoglg** [comment]
@chicco785 Alright, so let's close this pull request for now, but keeping the branch in case we need to look into this issue again.

**Pull request closed without merging**
