### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by jason-fox**
## Proposed changes

- Update Readme, add hitbox
- Update CSS to security variant
- Pin MKDocs libraries.

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [Contributor License Agreement][cla]
- [x] I have updated the [RELEASE NOTES][release]
- [ ] I have added tests that prove my fix is effective or that my
      feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

[cla]: https://raw.githubusercontent.com/orchestracities/anubis/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/anubis/blob/master/CONTRIBUTING.md
    "Contributing to Anubis"
[release]: https://github.com/orchestracities/anubis/blob/master/RELEASE_NOTES.md
    "Anubis Release Notes"

### CODE REVIEW

**Comment by jason-fox** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jason-fox** [comment]
recheckcla

**Comment by jason-fox** [comment]
Also someone with appropriate rights needs to add `https://anubis-pep.readthedocs.org`  as the repo's website.

Screenshot 2022-05-02 at 12 36 10

**Comment by chicco785** [comment]
thx @jason-fox , can you:
- fix md: https://github.com/orchestracities/anubis/runs/6255945919?check_suite_focus=true
- add a line in the RELEASE_NOTES.md doc

**Comment by jason-fox** [comment]
Fixed  9d2e8aa - I think.  The automated tests won't rerun without your permission.

**Review by chicco785 — APPROVED** [review]

**Pull request merged**
