### PR TITLE
Ordering added for consistency

### LINKED ISSUE #208: Order results when using pagination
**Describe the bug**
It looks like result sets aren't ordered when using pagination params, e.g.

- https://github.com/orchestracities/anubis/blob/master/anubis-management-api/anubis/tenants/operations.py#L27

Without order, pagination will be inconsistent, especially when you have lots of rows in the underlying DB table. For example two pages (as determined by the offset and limit params) may wind up having some rows in common:

```
table: [r1, r2, ..., r100]

offset = 0 && limit = 3   ~~~> [r1, r2, r3]
offset = 3 && limit = 3   ~~~> [r2, r3, r4]
```

**To Reproduce**
N/A

**Expected behavior**
All queries involving pagination should also have an order by clause.

**Additional context**
See e.g.
- https://www.postgresql.org/docs/current/queries-limit.html

> Thus, using different LIMIT/OFFSET values to select different subsets of a query result will
> give inconsistent results unless you enforce a predictable result ordering with ORDER BY

### PR DESCRIPTION
**Pull request by Cerfoglg**
## Proposed changes

Ordering added for consistency when trying to paginate. Fixes #208

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [Contributor License Agreement][cla]
- [x] I have updated the [RELEASE NOTES][release]
- [x] I have added tests that prove my fix is effective or that my
      feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

[cla]: https://raw.githubusercontent.com/orchestracities/anubis/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/anubis/blob/master/CONTRIBUTING.md
    "Contributing to Anubis"
[release]: https://github.com/orchestracities/anubis/blob/master/RELEASE_NOTES.md
    "Anubis Release Notes"

### CODE REVIEW

**Review by c0c0n3 — COMMENTED** [review]
great job! do we need order by for the two functions below too?

- https://github.com/orchestracities/anubis/blob/master/anubis-management-api/anubis/middleware/operations.py#L43
- https://github.com/orchestracities/anubis/blob/master/anubis-management-api/anubis/middleware/operations.py#L68

thoughts?

**Comment by Cerfoglg** [comment]
@c0c0n3 Actually yes, it would be good to order those as well. Pushing a quick fix.

**Comment by Cerfoglg** [comment]
Nevermind, trying to order those causes problems. Reverting the changes, we are not touching the middleware in this request.

**Review by c0c0n3 — APPROVED** [review]
cool, I'll open a separate issue to tackle the middleware tweaks.

**Pull request merged**
